name:                fizzbuzz-bot
version:             0.1.0.0
github:              "rosalogia/fizzbuzz-bot"
license:             BSD3
author:              "Ambika Eshwar"
maintainer:          "ambika.eshwar@rutgers.edu"
copyright:           "2020 Ambika Eshwar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rosalogia/fizzbuzz-bot#readme>

dependencies:
- base
- discord-haskell
- text
- unliftio
- aeson
- bytestring

library:
  source-dirs: src

executables:
  fizzbuzz-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fizzbuzz-bot

tests:
  fizzbuzz-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fizzbuzz-bot
